[platformio]
default_envs = esp32-s3

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-ota]
extends = env:esp32-s3
upload_protocol = espota

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
