; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-devkit-v1

[env:esp32-s3]
extra_scripts = pre:tools/build_id.py
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = h2zero/NimBLE-Arduino@^1.4.2
build_unflags = -std=gnu++11
build_flags =
	-std=gnu++17
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-ota]
extends = env:esp32-s3
upload_protocol = espota

[env:esp32-devkit-v1]
extends = env:esp32-s3
board = esp32dev
build_flags = -std=gnu++17
board_build.partitions = partitions/esp32dev-4mb.csv

[env:esp32-devkit-v1-ota]
extends = env:esp32-devkit-v1
upload_protocol = espota

[env:native]
platform = native
test_framework = unity
build_flags = -std=gnu++17
